use_frameworks!

target 'PHBApplying_Example' do
  pod 'PHBApplying', :path => '../'

  target 'PHBApplying_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
